server:
  port: 9090

spring:
  application:
    name: tool86-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/tool86db1
    username: tool86user1
    password: tool861
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
     redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 600000

jwt:
  secret: tool86_default_secret_key_1234567890
  expiration: 86400000

ai:
  service:
    url: http://localhost:5000